# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KeSiZgmhvmjwS9JCb-C4yS2XB-_u7wAi

# **String Rotation**

Rotate a given String in the specified direction by specified magnitude.

After each rotation make a note of the first character of the rotated String, After all rotation are performed the accumulated first character as noted previously will form another string, say **FIRSTCHARSTRING.**

Check If **FIRSTCHARSTRING** is an Anagram of any substring of the Original string.

If yes print **YES** otherwise **NO**.

**Input**


*   The first line contains the original string s. 
*   The second line contains a single integer q.

*   The ith line of the next q lines contains character d[i] denoting direction and integer r[i] denoting the magnitude.

**Output**

YES or NO

**Constraints**

1 <= Length of original string <= 30
1<= q <= 10

**Sample Input & Output**

**Input**

carrace

3

L 2

R 2

L 3

**Output**

NO

**Explanation**

After applying all the rotations the FIRSTCHARSTRING string will be rcr which is not anagram of any sub string of original string carrace
"""

s=input()
q=int(input())
f=''
while(q>0):
    d,r=input().split()
    r=int(r)
    c=0
    j=q
    if d=='L':
        s=s[r:]+s[:r]
        f=f+s[0]
        c=c+1
        
    elif d=='R':
        s=s[-r:]+s[:-r]
        f=f+s[0]
        c=c+1
    if(c==j):
        if f in s+s:
            print('YES')
        else:
            print('NO')
    q=q-1